# Generated by Django 5.2.6 on 2025-09-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.IntegerField(max_length=50)),
                ('img', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
            ],
        ),
    ]
