# Generated by Django 6.0 on 2025-12-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.CharField(max_length=50)),
                ('img', models.URLField(verbose_name='')),
                ('description', models.TextField()),
            ],
        ),
    ]
