# Generated by Django 5.2.6 on 2025-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categary_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categary',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(max_length=50),
        ),
    ]
